### ISSUE TITLE
Upload file fail on http status 419

### ISSUE THREAD

**Issue by jaycom** [webard/nova-suneditor#2]
When upload image, it's only call nova api to upload but missing set X-CSRF-TOKEN and X-XSRF-TOKEN

So it will return htttp status 419.
Is it can use Nova.request() to upload image?

**Comment by marcleonhard** [comment]
Same issue here.

**Comment by jaycom** [comment]
I fixed the issue.
Add the csrf_token in settings

```
namespace App\Nova\Fields;

use Webard\NovaSunEditor\SunEditor as WebardSunEditor;

class SunEditor extends WebardSunEditor {
    public function __construct( $name, $attribute = null, callable $resolveCallback = null ) {
        parent::__construct($name, $attribute, $resolveCallback);

        $this->settings([
            'imageUploadHeader' => [
                'X-CSRF-TOKEN' => csrf_token(),
            ]
        ]);
    }
}
```

**Comment by marcleonhard** [comment]
> I fixed the issue. Add the csrf_token in settings
> 
> ```
> namespace App\Nova\Fields;
> 
> use Webard\NovaSunEditor\SunEditor as WebardSunEditor;
> 
> class SunEditor extends WebardSunEditor {
>     public function __construct( $name, $attribute = null, callable $resolveCallback = null ) {
>         parent::__construct($name, $attribute, $resolveCallback);
> 
>         $this->settings([
>             'imageUploadHeader' => [
>                 'X-CSRF-TOKEN' => csrf_token(),
>             ]
>         ]);
>     }
> }
> ```

Thanks buddy!
